/*
 * This file is generated by jOOQ.
 */
package com.zsx.generator.jooq;


import com.zsx.generator.jooq.tables.Company;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Myschema extends SchemaImpl {

    private static final long serialVersionUID = 775506618;

    /**
     * The reference instance of <code>myschema</code>
     */
    public static final Myschema MYSCHEMA = new Myschema();

    /**
     * The table <code>myschema.company</code>.
     */
    public final Company COMPANY = com.zsx.generator.jooq.tables.Company.COMPANY;

    /**
     * No further instances allowed
     */
    private Myschema() {
        super("myschema", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Company.COMPANY);
    }
}
