/*
 * This file is generated by jOOQ.
 */
package com.zsx.generator.jooq;


import com.zsx.generator.jooq.tables.Company;

import javax.annotation.processing.Generated;


/**
 * Convenience access to all tables in myschema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>myschema.company</code>.
     */
    public static final Company COMPANY = Company.COMPANY;
}
